Repository Yamamoto1012/Rainy_jellyfish_project, pull requests merged in 2022-11, with the labels that each got.

#9 🐛 画面の表示エラーの修復
  manageroom/README.md
  manageroom/package-lock.json
  manageroom/src/App.css
  manageroom/src/App.js
  manageroom/src/components/Home.jsx
  manageroom/src/components/JoinRoom.jsx
  manageroom/src/components/Main.jsx
  manageroom/src/components/css/joinStyle.css
Labels: good first issue

#10 以下の項目を追加しました
  .DS_Store
  manageroom/public/index.html
  manageroom/src/App.js
  manageroom/src/components/Home.jsx
  manageroom/src/components/JoinRoom.jsx
  manageroom/src/components/Login.jsx
  manageroom/src/components/Main.jsx
  manageroom/src/components/css/login.css
  manageroom/src/components/css/main.css
  manageroom/src/components/profileus.jsx
  manageroom/src/images/logo.PNG
  manageroom/src/reset.css
Labels: enhancement

#12 横スクロール、縦スクロールができるようになった
  manageroom/src/components/JoinRoom.jsx
  manageroom/src/components/Main.jsx
  manageroom/src/components/css/main.css
  manageroom/src/images/chair.PNG
Labels: enhancement

#11 ページ更新
  Rainy_jellyfish_project - ショートカット.lnk
  manageroom/.vscode/launch.json
  manageroom/package-lock.json
  manageroom/package.json
  manageroom/src/components/Login.jsx
  manageroom/src/components/css/login.css
Labels: help wanted
